import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      "./vitest.host.config.ts",
      "./packages/*/vitest.config.ts",
      "./plugins/*/frontend/vitest.config.ts",
    ],
    allowOnly: false,
    restoreMocks: true,
    clearMocks: true,
    maxWorkers: 4,
    pool: "threads",
    fileParallelism: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "lcov"],
      reportsDirectory: "coverage",
      include: [
        "src/**/*.{ts,tsx}",
        "packages/plugin-testkit/src/**/*.ts",
        "plugins/*/frontend/src/**/*.{ts,tsx}",
      ],
      exclude: [
        "**/*.d.ts",
        "**/*.test.{ts,tsx}",
        "**/types.ts",
        "**/types/**",
        "**/main.tsx",
        "**/test/**",
        "packages/plugin-testkit/src/setup.ts",
        "src/shared/ui/**",
      ],
      thresholds: {
        statements: 27,
        branches: 27,
        functions: 27,
        lines: 27,
        "src/shared/components/{FileTree,IconNav,ResizeHandle}.tsx": {
          statements: 80,
          branches: 75,
          functions: 85,
          lines: 85,
        },
        "src/app/{sidebarPreferences,useSidebarPreferencesController}.ts": {
          statements: 95,
          branches: 83,
          functions: 91,
          lines: 96,
        },
        "src/modules/settings/SettingsPanel.tsx": {
          statements: 90,
          branches: 80,
          functions: 85,
          lines: 90,
        },
        "src/modules/git/components/{DiffPanel,DiffViewer}.tsx": {
          statements: 80,
          branches: 75,
          functions: 85,
          lines: 85,
        },
        "src/modules/flow/utils/*.ts": {
          statements: 95,
          branches: 90,
          functions: 95,
          lines: 95,
        },
        "src/modules/data/utils.ts": {
          statements: 95,
          branches: 85,
          functions: 100,
          lines: 95,
        },
        "src/platform/extensions/{api,bridge}.ts": {
          statements: 90,
          branches: 85,
          functions: 100,
          lines: 95,
        },
        "src/platform/extensions/ExtensionFrame.tsx": {
          statements: 85,
          branches: 80,
          functions: 90,
          lines: 90,
        },
        "plugins/attachment-manager/frontend/src/features/{inventory,domains}/model.ts": {
          statements: 90,
          branches: 85,
          functions: 90,
          lines: 90,
        },
        "plugins/attachment-manager/frontend/src/features/github-images/model.ts": {
          statements: 90,
          branches: 80,
          functions: 90,
          lines: 90,
        },
        "plugins/attachment-manager/frontend/src/tauri-core.ts": {
          statements: 90,
          branches: 80,
          functions: 90,
          lines: 90,
        },
        "packages/plugin-testkit/src/{host-method-cases,mock-host}.ts": {
          statements: 90,
          branches: 85,
          functions: 90,
          lines: 90,
        },
      },
    },
  },
});
